env:
  browser: true
  es2021: true
  node: true
  # es6: true
root: true
extends: airbnb-base
# overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: 
  no-console: 0
  import/no-extraneous-dependencies: [error, { devDependencies: true }]
  # no-restricted-syntax: ["off", "ForOfStatement"]
  no-param-reassign: 0
  # import/prefer-default-export: 0
  # class-methods-use-this: 0
  # no-promise-executor-return: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
